# Generated by Django 4.1.5 on 2023-04-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkapp', '0002_registertable1'),
    ]

    operations = [
        migrations.CreateModel(
            name='registertable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('npassword', models.CharField(max_length=30)),
                ('cpassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='registertable1',
        ),
    ]
