# Generated by Django 4.1.5 on 2023-04-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkapp', '0005_registertable3_delete_registertable1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registertable',
        ),
    ]
