# Generated by Django 4.1.5 on 2023-04-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkapp', '0006_delete_registertable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registertable3',
            new_name='registertable',
        ),
    ]
