# Generated by Django 4.1.5 on 2023-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkapp', '0010_remove_profile_contact_no_remove_profile_cpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
