# Generated by Django 4.1.5 on 2023-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkapp', '0011_profile_country_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.TextField(null=True),
        ),
    ]
