# Generated by Django 4.1.5 on 2023-05-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkapp', '0012_profile_company_profile_industry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='profiledb',
        ),
    ]
